In [6]:
import numpy as np

In [7]:
n = [1,2,3,4]
type(n)

list

In [8]:
m = np.array(n)
type(m)

numpy.ndarray

In [9]:
m

array([1, 2, 3, 4])

In [10]:
a = [1,3,2]
b = [4,0,2]

a+b

[1, 3, 2, 4, 0, 2]

In [11]:
np.array(c)

NameError: name 'c' is not defined

In [12]:
c

NameError: name 'c' is not defined

In [13]:
c = [1,3,2]

In [14]:
np.array(c)

array([1, 3, 2])

In [15]:
d = np.array(b)

In [16]:
d+c

array([5, 3, 4])

In [17]:
x = 0
np.array(x)


array(0)

In [18]:
x

0

In [19]:
x=[0]

In [20]:
x

[0]

In [21]:
np.array(x)

array([0])

In [23]:
x = np.arange(3,28,1,dtype=int)
x

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27])

In [24]:
x

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27])

In [25]:
y = np.array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [26]:
y

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [27]:
np.sort(y)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])